name = "Immersive Horizons"
author = "Pelayo-Chacon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c234a48a8fb0f366b17ff22fb165478d5f44598d707cab8362fdd470ab95e3bb"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
