name = "Immersive Horizons"
author = "Pelayo-Chacon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e54eeac2627cb3cb982451fe41a5d523d996e0ce6daf23d812773077b34eb398"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
