name = "Immersive Horizons"
author = "Pelayo-Chacon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb9cb958a61ac9b6f4d03f5aa87cbfe06e63bb424517da18f9dba8ccb5809102"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
